### ISSUE TITLE
Add support for other file extensions/image formats

### ISSUE THREAD

**Issue by Andre601** [MCBanners/banner-api#11]
By default does the banner come as a PNG.
This is fine but may increase storage needed for an image that mostly doesn't have any transparent parts in it.

So a suggestion would be, to add an option to choose between PNG and JPEG depending on your own preferences.

**Comment by simpleauthority** [comment]
Yeah, sure. We can do that. However, as it's not /actually/ a PNG image (i.e, not specifically rendered PNG (unless Spring magically is doing that, could be)). Reason for saying that is changing to JPEG may not even have any considerable effect on storage size.
