### ISSUE TITLE
Incorrect star visuals

### ISSUE THREAD

**Issue by HexedHero** [MCBanners/banner-api#156]
MCBanners shows a 4.8-star rating as 4.5 stars on the banner image whereas Spigot shows it as 5 stars on the page. 
![](https://api.mcbanners.com/banner/saved/CnLPmFfRxDwsZP.png)
https://www.spigotmc.org/resources/59318/

**Comment by darbyjack** [comment]
Fixed via: https://github.com/MCBanners/banner-api/commit/00a83fe94b6866c90a8d7d077f68ad984a8c4e81

Should be deployed with the next update.
