### ISSUE TITLE
Plugin icon issues?

### ISSUE THREAD

**Issue by Andre601** [MCBanners/banner-api#180]
Just recently noticed that a lot of banners from MCBanners no longer display the plugin's icon but the default Spigot Image instead.

Not sure if this issue is caused by MCBanners or by something on Spigot's end.

Screenshot:
![image](https://user-images.githubusercontent.com/11576465/182035617-129a38db-17f3-471e-8b7e-a9aac5b28027.png)

**Comment by darbyjack** [comment]
Been in talk with SpigotMC staff. This is related to some Cloudflare changes that SpigotMC did. Working on seeing if we can get an exception.

**Comment by darbyjack** [comment]
I've implemented a temp fix via https://github.com/MCBanners/banner-api/commit/af8ce6850e04b67a9ee53254c6c231e4b723db38 for the time being. Some of them should load again. Working with SpigotMC to get a better fix. Will leave open for now.

**Comment by darbyjack** [comment]
SpigotMC has implemented a fix on their end. I've reverted the project back to utilizing them via: https://github.com/MCBanners/banner-api/commit/3898e84d280ee01589b4a4c2b5acd468254c055e
