### ISSUE TITLE
Multiple Page stats failure

### ISSUE THREAD

**Issue by CMarcoo** [MCBanners/banner-api#294]
The API is not checking for multiple pages of resources for authors that have many resources, and is thus miscalculating the total download count when creating a banner.

Proof:
https://api.mcbanners.com/banner/saved/rVGlScqsuGjnZz.png

The issue is here:
https://github.com/MCBanners/banner-api/blob/master/src/main/java/com/mcbanners/bannerapi/net/upstream/SpigotClient.java#L39

The fix is to loop all pages starting at 1 until the response from the XenForo Resource Manager API is empty.

**Comment by CMarcoo** [comment]
(comment: this github issue has been altered by third party agents without the authorization of the committer)

**Comment by darbyjack** [comment]
Might have a fix here - https://github.com/MCBanners/banner-api/pull/296
