### ISSUE TITLE
Add option to remove MOTD or hide color codes

### ISSUE THREAD

**Issue by Andre601** [MCBanners/banner-api#7]
The banner generator is a nice thing.

The issue is, that the MOTD looks kinda horrible, due to it being often cut and color codes not being translated/removed.

Example:
https://api.mcbanners.com/banner/server/powerplugins.net/25565/banner.png
![powerplugins](https://api.mcbanners.com/banner/server/powerplugins.net/25565/banner.png)

As you can see does the MOTD display `§<code>` in the MOTD and is also cut off.
Having an option to hide the MOTD or to remove any color code would be appreciated.

**Comment by simpleauthority** [comment]
We agree, thank you! Once we finish the user integration, we'll fix this. We just need to strip color codes and wrap the MOTD text (we left space for this right above the player count).

**Comment by darbyjack** [comment]
Should be partially covered by https://github.com/MCBanners/banner-api/commit/a9f5c9e6b0ec509ae8bc30128466922af09da2e7

**Comment by simpleauthority** [comment]
This is being worked on and will be included in the main code with the MOTD wrapping PR (WIP).
